[package]
name = "joybus-pio"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
embedded-hal = "1.0.0"
pio = "0.2.1"
rp2040-hal = "0.10.0"
# broken with cargo bin deps nightly feature
#pio-proc = "0.2.2"
